version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./src:/projects"
    tty: true
    environment:
      TZ: Asia/Tokyo
      PORT: '5000'
    #ローカル用command
    command: flask run --host 0.0.0.0 --port 5000
    #デプロイ用command
    #command: flask run --port 5000
    